# https://mise.jdx.dev
[tools]
golangci-lint = "latest"
typos = "latest"
vhs = "latest"
"go:golang.org/x/pkgsite/cmd/pkgsite" = "latest"

[vars]
cov_data = "coverage.out"

[tasks.tidy]
description = "Tidy dependencies in go.mod and go.sum"
sources = ["**/*.go", "go.mod", "go.sum"]
run = "go mod tidy"

[tasks.fmt]
description = "Run go fmt on all source files"
sources = ["**/*.go", ".golangci.yml"]
run = "golangci-lint fmt ./..."

[tasks.demo]
description = "Render the demo gifs"
sources = ["docs/src/*.tape", "**/*.go"]
outputs = [".assets/*.gif"]
run = 'for file in ./docs/src/*.tape; do vhs "$file"; done'

[tasks.upload]
description = "Upload the demo gifs to my personal CDN. (Requires AWS auth)"
depends = "demo"
sources = [".assets/*.gif"]
run = "aws s3 cp .assets/ s3://assets.followtheprocess.codes/projects/log/ --recursive --sse AES256"

[tasks.test]
description = "Run the test suite"
sources = ["**/*.go", "go.mod", "go.sum", "**/testdata/**/*"]
# -race needs CGO
env = { CGO_ENABLED = "1" }
run = "go test -race ./..."

[tasks.bench]
description = "Run all project benchmarks"
sources = ["**/*.go"]
run = "go test ./... -run None -benchmem -bench ."

[tasks.lint]
description = "Run linting"
depends = ["fmt"]
sources = ["**/*.go", ".golangci.yml"]
run = ["golangci-lint run ./...", "typos"]

[tasks.doc]
description = "Render the pkg docs locally"
run = "pkgsite -open"

[tasks.cov]
description = "Calculate test coverage and render the html"
outputs = ["{{vars.cov_data}}"]
run = [
  "go test -race -cover -covermode atomic -coverprofile {{vars.cov_data}} ./...",
  "go tool cover -html {{vars.cov_data}}",
]

[tasks.check]
description = "Run tests and linting in one"
run = ["mise run test", "mise run lint"]

[tasks.sloc]
description = "Print lines of code"
run = "fd . -e go | xargs wc -l | sort -nr | head"

[tasks.clean]
description = "Remove build artifacts and other clutter"
run = ["go clean ./...", "rm -rf {{vars.cov_data}}"]

[tasks.update]
description = "Updates dependencies in go.mod and go.sum"
run = ["go get -u ./...", "go mod tidy"]
